# Generated by Django 2.1.5 on 2019-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190203_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
