# Generated by Django 2.1.5 on 2019-02-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
