# Generated by Django 2.1.5 on 2019-02-26 03:42

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190226_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/tyreestevenson/Dev/DigitalMarketplace/static_cdn/media'), upload_to=products.models.download_media_location),
        ),
    ]
